### ISSUE TITLE
sdcadm post-setup ha-manatee syntax

### ISSUE THREAD

**Issue by pannon** [joyent/sdcadm#2] opened 2015-02-04 21:56 UTC
Tried to create a manatee HA setup with the following syntax:
`sdcadm post-setup ha-manatee -s UUID_SRV1 -s UUID_SRV2` - failed
`sdcadm post-setup ha-manatee -s UUID_SRV1 UUID_SRV2` - failed
`sdcadm post-setup ha-manatee -s UUID_SRV1,UUID_SRV2` - failed
`sdcadm post-setup ha-manatee -s "UUID_SRV1 UUID_SRV2"` - failed

Also tried the same with `--server`, same results .

All of the above failing mostly with `Must specify 2 existing servers` or `Must specify 2 target servers`

What is the correct syntax for specifying servers? I might have overlooked something in the docs?

Thanks.

**Comment by trentm** [comment] 2015-02-04 22:14
Looking at the code `sdcadm post-setup ha-manatee -s UUID_SRV1 -s UUID_SRV2` should be the right way. I haven't yet used and tested `sdcadm post-setup ha-manatee` yet though. 

I was able to get past that like this:

```
[root@headnode (coal) ~]# sysinfo | json UUID
564d64ae-e5fd-99bb-60e9-f7aa0d58326f
[root@headnode (coal) ~]# sdcadm post-setup ha-manatee -s 564d64ae-e5fd-99bb-60e9-f7aa0d58326f -s 564d64ae-e5fd-99bb-60e9-f7aa0d58326f
Verifying target severs "["564d64ae-e5fd-99bb-60e9-f7aa0d58326f","564d64ae-e5fd-99bb-60e9-f7aa0d58326f"]" exist
Getting SDC application details from SAPI
Getting SDC's manatee details from SAPI
Getting SDC's manatee instances from SAPI
Getting primary manatee details from VMAPI

This command will make the following changes:

Add instance "manatee1" in server 564d64ae-e5fd-99bb-60e9-f7aa0d58326f
Add instance "manatee2" in server 564d64ae-e5fd-99bb-60e9-f7aa0d58326f
using image 982fcdba-a8c1-11e4-988b-33a5939f0bbf (sdc-postgres@master-20150130T204339Z-gffdeb9a)

Would you like to continue? [y/N]
```

Perhaps the UUID arguments you are giving are not existing and setup CNs in CNAPI (`sdc-cnapi /servers?setup=true`)?

A general warning: You've hit on something (sdcadm post-setup stuff) that is *very* new right now. We're doing a lot of work on `sdcadm` to get it up to snuff for production use. It isn't generally used for handlling SDC upgrades *quite* yet.

**Comment by kusor** [comment] 2015-02-06 15:45
Hi Peter,

as Trent said, `sdcadm post-setup ha-manatee -s UUID_SRV1 -s UUID_SRV2` is the way to proceed. Also, as Trent commented, the given server UUIDs must belong to existing servers on CNAPI. What is the output of `sdc-cnapi /servers/UUID_SRV1` and `sdc-cnapi /servers/UUID_SRV2` for the concrete UUIDs you tried to give to the command?.

**Comment by pannon** [comment] 2015-02-08 19:45
Guys sorry for the long delay on this, please see below.

Both `sdc-cnapi /servers/UUID_SRV1 sdc-cnapi /servers/UUID_SRV2` is finding the servers OK.
Also  `sdc-server list` is working as expected.


`sdcadm post-setup ha-manatee -s UUID_SRV1 -s UUID_SRV2` fails with:

```
Verifying target severs "["UUID_SRV1","UUID_SRV2"]" exist
sdcadm post-setup: error (Usage): Must specify 2 existing servers
```

Maybe it is only affecting our version, which is based on joyent_20150123T195942Z.

Meanwhile I have worked this around, just followed the HA setup guide in the Manatee documentation.

**Comment by trentm** [comment] 2015-02-17 23:50
@pannon  Possibly fixed by https://github.com/joyent/sdcadm/commit/f6209c5502cbe14660b56c5c2847e84db12f35af  just recently.

**Comment by kusor** [comment] 2015-02-18 09:10
Yeah, @pannon, GH-5 was a duplicate of this. It's fixed now.

**Closed by kusor** 2015-02-18 09:10 UTC
